name: Free RDP 6h

on: [workflow_dispatch]

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Baixar Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok_temp
          echo "Download concluído"

      - name: Configurar Ngrok
        run: .\ngrok_temp\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Abrir túnel RDP e mostrar link
        run: .\ngrok_temp\ngrok.exe tcp 3389 --log stdout
